language: java
jdk: oraclejdk11

before_install:
- chmod +x mvnw

env:
  global:
    secure: "TpwdgRM81lOoL2l2FBMnNFbTeRIShTdU5lbLOwO5K5q9EY8zZoiolLmRK/4spFKbHIa6xYh7et4cHFgJm67lf+92NicY1XDT7kACD6ZcKzZ+QbI+hTwHBU2izR93gihs82ixu4RNp2EwB5jqyelbySgV5fQWOqy0UrlTlaABZBnBT3UePhBvA91jeZbk2gh8atfjapzd5qHY389XnPRL7QBDvEayAPPl43l1t8X+XVYIqhLuBVqzZaa/yVpCC0w/d0bBeR8+rnuqZx6+bUDRDHq/ZsRDvmGjuJarNElNsdIhNiqmxk7HT0MF4nYdW1L4i4tVqe4petBXDgIH6VF9pPO7yJl518SJiBKy6Rj2iOgS/+ZQjeC1z9+Mk93u1rhjtP3c3nT30p+3yRPB35qHuHE0wIcAwtlsBibzO0ZTX8CdlqOmOQ4zNjtteVedxH2gGa4nHzkPQ5+pJhzEm0lDR3vljViUUKotoczHX2zzWzDwwQnDyL+sCDmKfR1jAPHQDPDwE/FFliHdgX40u8fGhEB7LdUPUlQsZ87DBqTus2I1+fMMvZP6WSOXrLt8qZ13GMvFGQwjq7oCsZNZxzLe0gkbQ3oSnIv/WZsFe5Ua5KqR4ZoAsxOpJcN5Nf+klnR0e58XW5XCegohJTgbarIWyR/EnYgyDxyAnCPHcLxfUII="

addons:
  sonarcloud:
    organization: "marcin007-todolist"
    token:
      secure: "TpwdgRM81lOoL2l2FBMnNFbTeRIShTdU5lbLOwO5K5q9EY8zZoiolLmRK/4spFKbHIa6xYh7et4cHFgJm67lf+92NicY1XDT7kACD6ZcKzZ+QbI+hTwHBU2izR93gihs82ixu4RNp2EwB5jqyelbySgV5fQWOqy0UrlTlaABZBnBT3UePhBvA91jeZbk2gh8atfjapzd5qHY389XnPRL7QBDvEayAPPl43l1t8X+XVYIqhLuBVqzZaa/yVpCC0w/d0bBeR8+rnuqZx6+bUDRDHq/ZsRDvmGjuJarNElNsdIhNiqmxk7HT0MF4nYdW1L4i4tVqe4petBXDgIH6VF9pPO7yJl518SJiBKy6Rj2iOgS/+ZQjeC1z9+Mk93u1rhjtP3c3nT30p+3yRPB35qHuHE0wIcAwtlsBibzO0ZTX8CdlqOmOQ4zNjtteVedxH2gGa4nHzkPQ5+pJhzEm0lDR3vljViUUKotoczHX2zzWzDwwQnDyL+sCDmKfR1jAPHQDPDwE/FFliHdgX40u8fGhEB7LdUPUlQsZ87DBqTus2I1+fMMvZP6WSOXrLt8qZ13GMvFGQwjq7oCsZNZxzLe0gkbQ3oSnIv/WZsFe5Ua5KqR4ZoAsxOpJcN5Nf+klnR0e58XW5XCegohJTgbarIWyR/EnYgyDxyAnCPHcLxfUII="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar